'''

Question:
You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.
Ex: Given the following strings:
s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''

'''

def findTheDifference(string1, string2):
    s = string1 + string2
    output = ''
    s_dict = {}
    for i in s:
        if i in s_dict.keys():
            s_dict[i] += 1
        else:
            s_dict[i] = 1
    for i in s:
            if s_dict[i] % 2 == 1:
                output += i
    return output

string1 = input("Enter the first string: ")
string2 = input("Enter the second string: ")
print("The added character is ",findTheDifference(string1,string2))